version: '3'
services:
  mysql-dev:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "3308:3306"
    volumes:
      - "./my.cnf:/etc/ysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"

  admin:
    image: adminer
    ports: 
      - "8080:8080"

  redis:
    image: redis:alpine

  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "sleep 2.5; npm run dev"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
    labels:
      - "traefik.enable=true"
      - ${TRAEFIK_FRONT}
    depends_on:
      - mysql-dev
      - redis
    ports:
      - "3000:3000"